version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cirlcci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: Greeting
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
